
-- Insert 10 dummy hajj packages with varying values
INSERT INTO hajj_packages (
    name,
    duration,
    duration_category,
    departure_city,
    departure_date,
    season_category,
    inclusions,
    exclusions,
    featured_image,
    package_category,
    maktab,
    type,
    class,
    max_capacity,
    available_spots,
    prices,
    makkah_hotel_name,
    makkah_hotel_category,
    makkah_hotel_distance,
    madinah_hotel_name,
    madinah_hotel_category,
    madinah_hotel_distance,
    meal_plan,
    flight_type,
    itinerary,
    terms_and_conditions,
    cancellation_policy,
    refund_policy,
    traveler_responsibilities,
    disclaimer,
    activities,
    status
) VALUES
(
    'Premium Hajj Package 2025',
    '25 Days / 24 Nights',
    'long',
    'Mumbai',
    '2025-06-15',
    'Hajj 2025',
    ARRAY['5 Star Hotels', 'Direct Flights', 'All Meals', 'VIP Transport', 'Guided Ziyarat', 'Laundry Service'],
    ARRAY['Personal Expenses', 'Shopping', 'Extra Meals'],
    '/public/umrah-package-banner.jpg',
    'Premium',
    'A',
    'Shifting',
    'Luxury',
    50,
    15,
    '{"sharing": {"adult": "450000", "child": "350000", "infant": "50000"}, "private": {"quad": "1600000", "triple": "1350000", "double": "900000"}}',
    'Swissotel Makkah',
    '5 star',
    '200',
    'Pullman Zamzam Madina',
    '5 star',
    '150',
    'Full-board',
    'Direct',
    '[{"title": "Day 1: Arrival in Jeddah", "description": "Airport pickup and transfer to Makkah hotel"}, {"title": "Day 2-7: Makkah", "description": "Umrah rituals and spiritual activities"}, {"title": "Day 8-15: Hajj Rituals", "description": "Complete Hajj pilgrimage including Mina, Arafat, Muzdalifah"}]',
    'Standard terms and conditions apply for all bookings',
    'Cancellation charges apply as per policy',
    'Full refund available until 90 days before departure',
    'Valid passport and visa required',
    'Travel insurance recommended',
    '["hajj-rituals", "ziyarat-tours", "spiritual-guidance"]',
    'active'
),
(
    'Economy Hajj Package 2025',
    '20 Days / 19 Nights',
    'medium',
    'Delhi',
    '2025-06-20',
    'Hajj 2025',
    ARRAY['3 Star Hotels', 'Group Flights', 'Breakfast & Dinner', 'Shared Transport', 'Basic Guidance'],
    ARRAY['Lunch', 'Personal Expenses', 'Laundry', 'Shopping'],
    '/public/placeholder.svg',
    'Economy',
    'C',
    'Non-Shifting',
    'Budget',
    80,
    25,
    '{"sharing": {"adult": "280000", "child": "220000", "infant": "30000"}, "private": {"quad": "950000", "triple": "800000", "double": "550000"}}',
    'Al Safwah Royale Orchid',
    '3 star',
    '800',
    'Rove Al Madinah',
    '3 star',
    '500',
    'Half-board',
    'Connecting',
    '[{"title": "Day 1: Departure", "description": "Flight from Delhi to Jeddah"}, {"title": "Day 2-8: Makkah Stay", "description": "Umrah and preparation for Hajj"}, {"title": "Day 9-16: Hajj Period", "description": "Complete Hajj rituals"}]',
    'Budget package terms apply',
    'Standard cancellation policy',
    'Partial refund available',
    'All documents must be valid',
    'Package subject to availability',
    '["hajj-rituals", "group-activities"]',
    'active'
),
(
    'Deluxe Family Hajj Package',
    '22 Days / 21 Nights',
    'medium',
    'Hyderabad',
    '2025-06-10',
    'Hajj 2025',
    ARRAY['4 Star Hotels', 'Family Suites', 'All Meals', 'Private Transport', 'Family Guidance', 'Kids Care'],
    ARRAY['Personal Shopping', 'Extra Activities', 'Spa Services'],
    '/public/umrah-package-banner.jpg',
    'Family',
    'B',
    'Shifting',
    'Deluxe',
    60,
    18,
    '{"sharing": {"adult": "380000", "child": "280000", "infant": "40000"}, "private": {"quad": "1300000", "triple": "1100000", "double": "750000"}}',
    'Hilton Suites Makkah',
    '4 star',
    '400',
    'Marriott Madinah',
    '4 star',
    '300',
    'Full-board',
    'Direct',
    '[{"title": "Day 1-2: Travel & Arrival", "description": "Journey to Makkah with family comfort"}, {"title": "Day 3-10: Makkah Family Time", "description": "Umrah with special family arrangements"}, {"title": "Day 11-18: Hajj with Family", "description": "Family-friendly Hajj experience"}]',
    'Family package special terms',
    'Family-friendly cancellation policy',
    'Family package refund terms',
    'Family travel documentation required',
    'Child safety measures included',
    '["family-activities", "hajj-rituals", "kids-programs"]',
    'active'
),
(
    'VIP Luxury Hajj Experience',
    '30 Days / 29 Nights',
    'long',
    'Bangalore',
    '2025-06-05',
    'Hajj 2025',
    ARRAY['5 Star Luxury Hotels', 'Business Class Flights', 'Fine Dining', 'Personal Butler', 'Private Ziyarat', 'Spa Access'],
    ARRAY['Personal Shopping Beyond Allowance', 'Additional Spa Treatments'],
    '/public/umrah-package-banner.jpg',
    'VIP',
    'A',
    'Shifting',
    'Luxury',
    20,
    5,
    '{"sharing": {"adult": "750000", "child": "550000", "infant": "75000"}, "private": {"quad": "2800000", "triple": "2400000", "double": "1600000"}}',
    'Fairmont Makkah Clock Royal Tower',
    '5 star',
    '50',
    'Anantara Madinah',
    '5 star',
    '100',
    'Full-board',
    'Direct',
    '[{"title": "Day 1-3: Luxury Arrival", "description": "VIP arrival and luxury accommodation setup"}, {"title": "Day 4-15: Extended Makkah Stay", "description": "Luxury Umrah experience with personal services"}, {"title": "Day 16-25: VIP Hajj", "description": "Premium Hajj experience with all comforts"}]',
    'VIP package exclusive terms',
    'Flexible cancellation for VIP guests',
    'Premium refund policy',
    'VIP documentation assistance',
    'Luxury service standards apply',
    '["vip-services", "luxury-experiences", "personal-guidance"]',
    'active'
),
(
    'Youth Group Hajj Package',
    '18 Days / 17 Nights',
    'short',
    'Chennai',
    '2025-06-25',
    'Hajj 2025',
    ARRAY['Youth Hostels', 'Group Activities', 'Educational Programs', 'Shared Transport', 'Youth Mentorship'],
    ARRAY['Personal Expenses', 'Individual Activities', 'Extra Meals'],
    '/public/placeholder.svg',
    'Youth',
    'D',
    'Non-Shifting',
    'Budget',
    100,
    40,
    '{"sharing": {"adult": "250000", "child": "200000", "infant": "25000"}, "private": {"quad": "850000", "triple": "700000", "double": "480000"}}',
    'Youth Accommodation Makkah',
    '2 star',
    '1200',
    'Budget Stay Madinah',
    '2 star',
    '800',
    'Breakfast',
    'Connecting',
    '[{"title": "Day 1: Group Departure", "description": "Youth group departure with orientation"}, {"title": "Day 2-8: Makkah Learning", "description": "Educational Umrah experience"}, {"title": "Day 9-15: Youth Hajj", "description": "Guided Hajj experience for young pilgrims"}]',
    'Youth group terms and conditions',
    'Group cancellation policy',
    'Youth package refund terms',
    'Parental consent required for minors',
    'Youth safety protocols in place',
    '["youth-programs", "educational-tours", "group-activities"]',
    'active'
),
(
    'Senior Citizens Hajj Package',
    '28 Days / 27 Nights',
    'long',
    'Kolkata',
    '2025-06-08',
    'Hajj 2025',
    ARRAY['Senior-Friendly Hotels', 'Medical Support', 'Wheelchair Access', 'Special Meals', 'Gentle Guidance', 'Health Monitoring'],
    ARRAY['Additional Medical Services', 'Personal Care Beyond Basic'],
    '/public/umrah-package-banner.jpg',
    'Senior',
    'B',
    'Non-Shifting',
    'Deluxe',
    30,
    8,
    '{"sharing": {"adult": "420000", "child": "320000", "infant": "35000"}, "private": {"quad": "1400000", "triple": "1200000", "double": "800000"}}',
    'Senior Care Makkah Hotel',
    '4 star',
    '600',
    'Comfort Madinah',
    '4 star',
    '400',
    'Full-board',
    'Direct',
    '[{"title": "Day 1-3: Comfortable Arrival", "description": "Senior-friendly arrival and settling"}, {"title": "Day 4-15: Gentle Makkah Stay", "description": "Comfortable Umrah with health support"}, {"title": "Day 16-25: Assisted Hajj", "description": "Hajj with medical and mobility support"}]',
    'Senior citizen special terms',
    'Flexible cancellation for health reasons',
    'Senior-friendly refund policy',
    'Medical clearance required',
    'Health and safety priority',
    '["senior-care", "medical-support", "accessibility"]',
    'active'
),
(
    'Express Hajj Package',
    '15 Days / 14 Nights',
    'short',
    'Ahmedabad',
    '2025-06-30',
    'Hajj 2025',
    ARRAY['Express Hotels', 'Quick Processing', 'Fast Track Services', 'Efficient Transport', 'Time-Optimized'],
    ARRAY['Extended Activities', 'Leisure Time', 'Non-Essential Services'],
    '/public/placeholder.svg',
    'Express',
    'C',
    'Shifting',
    'Premium',
    40,
    12,
    '{"sharing": {"adult": "350000", "child": "270000", "infant": "35000"}, "private": {"quad": "1200000", "triple": "1000000", "double": "680000"}}',
    'Express Makkah Hotel',
    '3 star',
    '500',
    'Quick Stay Madinah',
    '3 star',
    '600',
    'Half-board',
    'Direct',
    '[{"title": "Day 1: Quick Arrival", "description": "Fast-track arrival and immediate accommodation"}, {"title": "Day 2-6: Express Umrah", "description": "Efficient Umrah completion"}, {"title": "Day 7-13: Rapid Hajj", "description": "Time-optimized Hajj experience"}]',
    'Express package terms apply',
    'Limited cancellation window',
    'Express refund processing',
    'Quick documentation required',
    'Time-sensitive package',
    '["express-services", "time-efficient", "quick-processing"]',
    'active'
),
(
    'Comfort Plus Hajj Package',
    '24 Days / 23 Nights',
    'medium',
    'Pune',
    '2025-06-12',
    'Hajj 2025',
    ARRAY['Comfort Hotels', 'Balanced Services', 'Good Meals', 'Reliable Transport', 'Standard Guidance', 'Air Conditioning'],
    ARRAY['Luxury Upgrades', 'Premium Services', 'Personal Shopping'],
    '/public/umrah-package-banner.jpg',
    'Comfort',
    'B',
    'Shifting',
    'Deluxe',
    70,
    22,
    '{"sharing": {"adult": "320000", "child": "250000", "infant": "32000"}, "private": {"quad": "1100000", "triple": "950000", "double": "650000"}}',
    'Comfort Inn Makkah',
    '3 star',
    '700',
    'Peaceful Madinah',
    '3 star',
    '550',
    'Full-board',
    'Connecting',
    '[{"title": "Day 1-2: Comfortable Journey", "description": "Pleasant travel and arrival"}, {"title": "Day 3-12: Makkah Comfort", "description": "Comfortable Umrah experience"}, {"title": "Day 13-21: Balanced Hajj", "description": "Well-balanced Hajj journey"}]',
    'Comfort package standard terms',
    'Reasonable cancellation policy',
    'Fair refund terms',
    'Standard documentation',
    'Balanced service expectations',
    '["comfort-services", "balanced-experience", "standard-amenities"]',
    'active'
),
(
    'Educational Hajj Package',
    '26 Days / 25 Nights',
    'long',
    'Lucknow',
    '2025-06-18',
    'Hajj 2025',
    ARRAY['Educational Sessions', 'Historical Tours', 'Islamic Studies', 'Scholarly Guidance', 'Library Access', 'Academic Materials'],
    ARRAY['Non-Academic Activities', 'Entertainment', 'Recreational Tours'],
    '/public/placeholder.svg',
    'Educational',
    'A',
    'Non-Shifting',
    'Premium',
    45,
    15,
    '{"sharing": {"adult": "400000", "child": "300000", "infant": "40000"}, "private": {"quad": "1350000", "triple": "1150000", "double": "780000"}}',
    'Scholar Makkah Residence',
    '4 star',
    '350',
    'Academic Madinah',
    '4 star',
    '250',
    'Full-board',
    'Direct',
    '[{"title": "Day 1-3: Academic Orientation", "description": "Introduction to Islamic history and Hajj significance"}, {"title": "Day 4-14: Scholarly Makkah", "description": "Educational Umrah with historical context"}, {"title": "Day 15-23: Academic Hajj", "description": "Hajj with deep understanding and learning"}]',
    'Educational package academic terms',
    'Academic cancellation policy',
    'Educational refund structure',
    'Academic credentials helpful',
    'Learning-focused experience',
    '["educational-tours", "academic-guidance", "historical-learning"]',
    'active'
),
(
    'Special Needs Hajj Package',
    '27 Days / 26 Nights',
    'long',
    'Jaipur',
    '2025-06-14',
    'Hajj 2025',
    ARRAY['Accessible Hotels', 'Special Care', 'Medical Support', 'Adaptive Equipment', 'Personal Assistance', 'Customized Services'],
    ARRAY['Standard Services', 'Non-Adaptive Equipment', 'General Activities'],
    '/public/umrah-package-banner.jpg',
    'Special Needs',
    'A',
    'Non-Shifting',
    'Premium',
    25,
    7,
    '{"sharing": {"adult": "480000", "child": "380000", "infant": "45000"}, "private": {"quad": "1650000", "triple": "1400000", "double": "950000"}}',
    'Accessible Makkah Hotel',
    '4 star',
    '300',
    'Barrier-Free Madinah',
    '4 star',
    '200',
    'Full-board',
    'Direct',
    '[{"title": "Day 1-4: Adaptive Arrival", "description": "Specialized arrival and accommodation setup"}, {"title": "Day 5-16: Supported Makkah", "description": "Accessible Umrah with full support"}, {"title": "Day 17-25: Assisted Hajj", "description": "Fully supported Hajj experience"}]',
    'Special needs accommodation terms',
    'Flexible health-based cancellation',
    'Adaptive refund policy',
    'Medical documentation required',
    'Specialized care standards',
    '["accessibility", "special-care", "adaptive-services"]',
    'active'
);
